version: '3.8'

services:
  adonis_app:
    container_name: adonis_app
    restart: always
    build:
      context: .
      target: dependencies
    ports:
      - 3333:3333
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
      # Uncomment the below line if you developing on MacOS
      #- /home/node/app/node_modules
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: jXJuTpEeI0root
      MYSQL_DATABASE: apidb
      MYSQL_USER: bhayron
      MYSQL_PASSWORD: jXJuTpEeI0

  db2:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: jXJuTpEeI0root
      MYSQL_DATABASE: apidb
      MYSQL_USER: bhayron
      MYSQL_PASSWORD: jXJuTpEeI0

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - db
